### ISSUE TITLE
New release to allow google-cloud-logging 3.0?

### ISSUE THREAD

**Issue by snarfed** [googleapis/python-error-reporting#227]
Hi all! First off, thank you for maintaining this library. We all appreciate it!

google-cloud-logging 3.0 is out, but google-cloud-error-reporting restricts its dependencies pretty narrowly, so 1.4.1 doesn't support 3.0. Looks like that constraint is already updated in #224  though, any chance you could cut a release with it?

More broadly, #224 still restricts to `google-cloud-logging>=1.14.0, <3.0.1`, so we'll have this exact same problem with the next google-cloud-logging release. Ideally libraries should be more permissive in their dependency constraints to avoid this problem. Consider relaxing it to `<4.0`, or something similar?

**Comment by johan-torres-data** [comment]
Hi everyone, thanks a lot for your effort in supporting issues related to error_reporting.
Working with `python 3.8.5` and the same problem here with the dependencies:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-error-reporting 1.4.1 requires google-cloud-logging<3.0.0dev,>=1.14.0, but you have google-cloud-logging 3.0.0 which is incompatible.`

**Comment by daniel-sanche** [comment]
Thanks for reporting this, I started the process to release v1.5.0, which should fix this issue

**Comment by snarfed** [comment]
Thank you @daniel-sanche!

Any thoughts on this part though? 

> More broadly, #224 still restricts to `google-cloud-logging>=1.14.0, <3.0.1`, so we'll have this exact same problem with the next google-cloud-logging release. Ideally libraries should be more permissive in their dependency constraints to avoid this problem. Consider relaxing it to `<4.0`, or something similar?

The same problem happened a while ago in https://github.com/googleapis/python-error-reporting/issues/92, and it will happen again as soon as google-cloud-logging cuts their next release, since your current version specifier in `setup.py` is `google-cloud-logging>=1.14.0, <3.0.1`. Libraries are generally expected to have looser dependency version specifiers, if any, to avoid exactly this problem. Any chance you could configure your renovate bot to relax the upper bound to at least the next major version (assuming semver), eg `<4.0`?

**Comment by snarfed** [comment]
Thank you all!
