### ISSUE TITLE
How to change the service name from python to the appropriate service in which error was reported

### ISSUE THREAD

**Issue by alizaidi606** [googleapis/python-error-reporting#275]
<img width="1657" alt="Screenshot 2022-05-11 at 2 38 29 PM" src="https://user-images.githubusercontent.com/13392803/167819635-79c3be02-9851-4ea9-8590-39b6c26b55e6.png">
<img width="1657" alt="Screenshot 2022-05-11 at 2 39 07 PM" src="https://user-images.githubusercontent.com/13392803/167819665-1bc547c2-d6f3-4027-9245-bdbd70db8d94.png">

As it can be seen in these screenshots that when an error is reported using this library it shows `python` as the service name in error reporting, which makes it hard to identify the actual service in which the error was reported.

Is there a way to modify this?
I am using the sample provided in the doc
```

from google.cloud import error_reporting
client = error_reporting.Client()
client.report_exception(e)
```

**Comment by minherz** [comment]
hi, i believe that what you see there is a _default_ name of the log. You can provide a different name in the `Client` constructor. Use [`service`](https://github.com/googleapis/python-error-reporting/blob/b2a0aaf56c3f85960f3c11fb65f5a77703009e44/google/cloud/error_reporting/client.py#L156) parameter to provide a custom name.
