### ISSUE TITLE
New docs not generated for googleapis.dev

### ISSUE THREAD

**Issue by epitstickpan** [googleapis/python-error-reporting#32]
#### Environment details

  - OSX 10.15.7
  - Python 3.8.5 from pyenv
  - pip 20.2.3
  - Version: 1.0.0

#### Steps to reproduce

  1. Go to https://googleapis.dev/python/clouderrorreporting/latest/gapic/v1beta1/api.html and see the version is 0.34
  2. Go to https://github.com/googleapis/python-error-reporting/ and see latest version is 1.0.0
  3. Try running the example [here](https://googleapis.dev/python/clouderrorreporting/latest/gapic/v1beta1/api.html#google.cloud.errorreporting_v1beta1.ErrorStatsServiceClient.list_events) on the latest version and see it doesn't work.

#### Code example

```
❯ pipenv run ipython
Loading .env environment variables…
Python 3.8.5 (default, Jul 23 2020, 07:01:23)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from google.cloud import error_reporting, errorreporting_v1beta1

In [2]: error_reporting.__version__
Out[2]: '1.0.0'

In [3]: client = errorreporting_v1beta1.ErrorStatsServiceClient()

In [4]: project_name = client.project_path('projects/<redacted>')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-2f1c97c8e71b> in <module>
----> 1 project_name = client.project_path('projects/<redacted>')

AttributeError: 'ErrorStatsServiceClient' object has no attribute 'project_path'
```

**Comment by Daniel-Sanche** [comment]
I'm seeing Version 1.0.0 on googleapis.dev, so I'm assuming this has been fixed
