### ISSUE TITLE
error raised when google-cloud-logging 2.0.0 is installed with google-cloud-error-reporting

### ISSUE THREAD

**Issue by hilliao** [googleapis/python-error-reporting#42]
### steps to reproduce
1. in a python3.8 virtual environment, execute the following commands:

`pip3 install google-cloud-logging=="2.0.0" && pip3 install google-cloud-error-reporting`

2. verify the installed:

```
Package                      Version  
---------------------------- ---------
cachetools                   4.1.1    
certifi                      2020.11.8
chardet                      3.0.4    
google-api-core              1.23.0   
google-auth                  1.23.0   
google-cloud-core            1.4.3    
google-cloud-error-reporting 1.0.0    
google-cloud-logging         2.0.0    
googleapis-common-protos     1.52.0   
grpcio                       1.33.2   
idna                         2.10     
libcst                       0.3.14   
mypy-extensions              0.4.3    
pip                          20.0.2   
pkg-resources                0.0.0    
proto-plus                   1.11.0   
protobuf                     3.14.0   
pyasn1                       0.4.8    
pyasn1-modules               0.2.8    
pytz                         2020.4   
PyYAML                       5.3.1    
requests                     2.25.0   
rsa                          4.6      
setuptools                   44.0.0   
six                          1.15.0   
typing-extensions            3.7.4.3  
typing-inspect               0.6.0    
urllib3                      1.26.2   
```

3. execute the python interpreter and 1 import line of code

```
 python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import error_reporting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hil/tmp/.m2/lib/python3.8/site-packages/google/cloud/error_reporting/__init__.py", line 22, in <module>
    from google.cloud.error_reporting.client import Client
  File "/home/hil/tmp/.m2/lib/python3.8/site-packages/google/cloud/error_reporting/client.py", line 35, in <module>
    from google.cloud.error_reporting._logging import _ErrorReportingLoggingAPI
  File "/home/hil/tmp/.m2/lib/python3.8/site-packages/google/cloud/error_reporting/_logging.py", line 22, in <module>
    import google.cloud.logging.client
ModuleNotFoundError: No module named 'google.cloud.logging.client'
>>> 
```

the error does not happen with google-cloud-logging         1.15.1; I suspect the error reporting fails to import the latest logging client library 2.0.0. Please investigate.

**Comment by Daniel-Sanche** [comment]
You're right, we'll have to push a v2.0.0 release for cloud-error-reporting soon to fix compatibility. Unfortunately, we're in a release freeze until after thanksgiving, so it may have to wait a couple weeks

It looks like the package declares its dependency requirement as `google-cloud-logging<2.0dev,>=1.14.0` though, and pip does its best to use compatible versions. Is this incompatibility creating any issues on your end?

**Comment by hilliao** [comment]
Somehow with the following Dockerfile content and requirements.txt, cloud logging 2.0.0 is installed

```
RUN pip install gunicorn
RUN pip install -r requirements.txt

google-api-python-client
google-auth
google-auth-httplib2
Flask
google-cloud-logging
grpcio
google-python-cloud-debugger
google-cloud-trace>=0.20.0,<1.0.0
opencensus
opencensus-ext-stackdriver
gcloud
google-cloud-secret-manager
google-cloud-error-reporting
```

I created a simplified steps to reproduce after I encountered the error. I am setting `google-cloud-logging==1.15.1` to work around it. It'd be ideal to enable google-cloud-error-reporting to work with google-cloud-logging >=2.0.0.

**Comment by Daniel-Sanche** [comment]
Ok, yeah I pushed a fix today to allow the latest versions to work together, but it won't be released until after thanksgiving due to the code freeze. I'll give an update here when it is

Thanks for reporting the issue

**Comment by Daniel-Sanche** [comment]
v1.1.0 has been pushed with this issue fixed
