### ISSUE TITLE
Bump google-cloud-logging version specifier to be compatible with 2.3 (ideally 2.x)

### ISSUE THREAD

**Issue by snarfed** [googleapis/python-error-reporting#92]
HI all! Thank you for building and maintaining google-cloud-error-reporting. It's great!

google-cloud-logging recently released a new version, 2.3, but google-cloud-error-reporting isn't compatible with it because of this version specifier in `setup.py`:

https://github.com/googleapis/python-error-reporting/blob/eaf4a5aebe9f3cee0af211defec7ff10d5bae4a4/setup.py#L32

Pip log:

```sh
$ pip install google-cloud-error-reporting==1.1.1 google-cloud-logging==2.3
...
ERROR: Cannot install google-cloud-error-reporting==1.1.1 and google-cloud-logging==2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested google-cloud-logging==2.3
    google-cloud-error-reporting 1.1.1 depends on google-cloud-logging<2.2 and >=1.14.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Basically the same issue as #42. Mind bumping that line to `<3.0`? I know 2.0 was a big backward incompatible release, but semver willing, hopefully there won't be another one of those until 3.0.

Thanks in advance!

#### Environment details

  - OS type and version: Ubuntu, Mac OS 11.2.3
  - Python version: 3.7.3, 3.9.2
  - pip version: , 21.0.1
  - `google-cloud-error-reporting` version: 1.1.1

**Comment by daniel-sanche** [comment]
Yes, thanks for catching that! I merged the [dependency PR](https://github.com/googleapis/python-error-reporting/pull/95), and will cut a new release this week
